In [33]:
import numpy as np
list_ = [ '1','2', '3', '4', '5' ]
array_list = np.array(object = list_)

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.**

In [34]:
print(type(list_)) 
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


**Answer1: Yes, there differences of datatypes between lsit_ and array_list. list_ is a object of python while array_list is the numpy array object** 

**Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.**

In [35]:
# Answer 2:
# printing datatypes of all the elements in list_and array_list

for i in list_ and array_list:
    print(type(i))
    print(type(array_list))

<class 'numpy.str_'>
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.ndarray'>


**Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)**

In [36]:
#answer:
array_list=np.array(object=list_,dtype=int)
for element in list_:
    print(type(element))
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


**Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size**

In [38]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [39]:
num_array.shape

(2, 3)

In [40]:
num_array.size

6

In [42]:
matrix=np.zeros((3,3))

In [43]:
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [47]:
identity_matrix = np.eye(5)

In [ ]:
print